# Generated by Django 5.1 on 2024-08-30 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_newsletter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='username',
        ),
    ]
