# Generated by Django 5.1 on 2024-08-13 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'پست'},
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(help_text='type something'),
        ),
    ]
