# Generated by Django 5.1 on 2024-08-13 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_options_alter_post_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name_plural': 'پست'},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='publishe_date',
            new_name='published_date',
        ),
    ]
