# Generated by Django 5.1 on 2024-08-21 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_comment_user_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(help_text='A valid email address, please.', max_length=254),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='users/un-user.jpg', upload_to='users/'),
        ),
    ]
